name: CI Workflow

on:
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      
      - uses: actions/setup-node@v5
        with:
          node-version: 22
      
      - run: npm ci

      - name: Formatting Check
        run: npm run check-format

      - name: Linting Check
        run: npm run lint

      - name: Type Check
        run: npm run type-check
